[package]
name = "rtb"
version = "0.1.2"
description = "Raven Task Board desktop app"
authors = ["NeMarusia"]
edition = "2021"

[lib]
name = "rtb_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.15"
